//speech.indexOf("heytony") >= 0 || speech.indexOf("atony") >= 0 || speech.indexOf("atoni") >= 0 || speech.indexOf("attorney") >= 0 || speech.indexOf("") >= 0 || speech.indexOf("") >= 0

module.exports = ["Hey banks",
    "big banks",
    "citibank",
    "a bank",
    "thanks",
    "a banks",
    "Expense",
    "the banks",
    "ebay",
    "thankthank",
    "Maybank",
    "big bang",
    "ibanks",
    "thebank",
    "event",
    "Hey beats",
    "hey babe",
    "hey mates",
    "debate",
    "abate",
    "teammates",
    "ebates",
    "playmates",
    "hey man",
    "whichway",
    "budget",
    "St bank",
    "okay pi"]